apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deployment-validation
  namespace: production
webhooks:
  - name: "deployment-validation.production.svc"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["production"]
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope: "Namespaced"
    clientConfig:
      url: https://e10d-2804-7f1-e283-f1b-183e-e532-1259-32a8.ngrok-free.app/admission-deployment
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 30
